### ISSUE TITLE
Type Provider

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#1]
Create an type provider that erases **to** the OWIN dictionary. Perhaps this could use types from System.Net.Http at design time. Benefits include increased performance since mapping completes at design time rather than runtime.

I would also like to push this all the way down to the network stream rather than starting with an OWIN IDictionary.

**Comment by kolektiv** [comment]
Probably this can be closed now - future type provider based ideas should probably get their own issue (such as potential type provider usage for strongly typed routing, templating, etc.)

**Comment by panesofglass** [comment]
I agree.
