### ISSUE TITLE
Freya projects

### ISSUE THREAD

**Issue by slav** [freya-fs/freya#108]
When I go to https://www.nuget.org/packages?q=freya I'm seeing quite a bit of projects. In addition there're also related Arachne projects. It would be nice if documentation reflected on all of them to explain what each of them does.

Also, in examples I saw reference to Freya.Inspector, Freya.Machine.Inspector and Freya.Router.Inspector. They're not in nuget. I'm guessing these are part of the debugging/tracing "module"?

**Comment by kolektiv** [comment]
I've gone through NuGet and cleaned the obsolete packages, NuGet was being slightly funny about listing things that should have been hidden! Hopefully that shouldn't happen now. I agree about the value of a page giving a package overview - we'll try and get that done soon.

The Freya Inspector work is part of the debug/trace system, and we should probably remove those from tutorials for now, as they're not production ready yet. I'll look at where we reference those and get that sorted.

**Comment by panesofglass** [comment]
@kolektiv I'll work on adding brief descriptions to the docs and README this week.

**Comment by panesofglass** [comment]
I added descriptions to the README with links to the docs. I'm going to close this. Please reopen if you think we need to do more.
