### ISSUE TITLE
Freya.Types - production ready?

### ISSUE THREAD

**Issue by slav** [freya-fs/freya#109]
I thought Freya is 1.0? But https://www.nuget.org/packages/Freya.Types/ is still in pre-release on nuget. Was it just not updated? Or should we not use it?

**Comment by kolektiv** [comment]
Yes, as mentioned in the other thread, Freya.Types is now obsolete. Generally speaking at the moment, you should only need to install the "Freya" package - it's a package which will always require the latest versions of the current stack, so you don't usually need to worry about picking and choosing. Just installing "Freya" should always give you everything production-ready for a complete system.

**Comment by panesofglass** [comment]
@kolektiv I'll work on adding brief descriptions to the docs and README this week.

**Comment by panesofglass** [comment]
See #108.
