### ISSUE TITLE
Should handleNoContent expect a Specification -> Freya<Representation>?

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#116]
@pblasucci brought up a good point in that it seems `handleNoContent` should return, possibly, a `Freya<unit>`. I know that breaks symmetry, but the underlying computation should be able to send a default, empty representation each time.

**Comment by pblasucci** [comment]
If breaking the symmetry is a show-stopper, maybe at the very least a `Representation.empty` instance could be provided?

**Comment by kolektiv** [comment]
Yes to both I think there, although the most pragmatic way to do so may be
a Representation.empty instance, which would maintain the simplicity at
least.

**Comment by kolektiv** [comment]
Representation.empty is present in the codebase now, which I think will be the right answer for 3.0.

**Comment by kolektiv** [comment]
Closing this, as will be sufficient for 3.0.
