### ISSUE TITLE
Is it possible to use a JSON serializer other than Chiron?

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#120]
If so, why is Chiron a dependency? (I'm assuming it's to support the Recorder.)
If not, we definitely need to start writing docs for Chiron! :)

**Comment by kolektiv** [comment]
Yes Chiron is purely there to support recording. I've got a branch
somewhere which moves the Chiron requirement out in to the (optional)
inspectors, so that will remove the common use. Chiron (for normal Freya,
rather than the hypermedia bits) isn't a requirement (or won't be...)

**Comment by kolektiv** [comment]
This has actually gone now from anything in the standard Freya distribution. Will only be needed for future inspectors. Closing as fixed I think!
