### ISSUE TITLE
Embed Router in Machine

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#140]
I had a thought this morning that I think it would be nice to embed the UriTemplate for a resource (or `FreyaMachine`) in the definition of the resource, e.g.

``` fsharp
let todoUri =
    UriTemplate.Parse "/{id}" 
let todo =
    freyaMachine todoUri {
        including common
        corsMethodsSupported todoMethods
        methodsSupported todoMethods
        doDelete deleteAction
        doPatch updateAction
        handleOk getHandler }
```

Then we could use a merge function to bind resources together:

``` fsharp
let app : Freya.Pipeline = FreyaMachine.merge [ todos; todo ]
```

Thoughts? Rather than breaking `freyaMachine` in this way we could create another abstraction layer, e.g. `freyaResource`, to wrap `FreyaMachine` with `Freya.Machine.Router`.

**Comment by kolektiv** [comment]
I think for now having them decoupled is useful, and with potential enhancements for 4.0+ we'll probably discover the answer. Closing for now, with potentially a feature issue to open for a new abstraction layer.
