### ISSUE TITLE
Update documentation for 2.0

### ISSUE THREAD

**Issue by SimonGustavsson** [freya-fs/freya#142]
I just upgraded to 2.0 and much to my surprise my error window was absolutely filled with Obsolete warnings. Mostly about Freya.get/set-Lens/LensPartial, accessing uppercase members of Request/Response and a fair few FreyaMachine.toPipeline.

As far as I can tell, the docs have no mention of the new `Freya.Optic` way of doing things.

For bonus points:
On the topic of Optic, are you expected to write code such as `do! Freya.Optic.set Response.statuscode_ (Some 404)` ? Only asking because my code just got longer and I'm not sure why. :-)

**Comment by panesofglass** [comment]
Oh no! Looks like the 2.0 versions were updated with a pre-release version of some dependencies. That was not intended. Those changes are primarily heading toward the 3.0 branch, which is a pre-release. Feel free to ignore those warnings for now and apologies for the inconvenience. On the other hand, you get a preview of where we are going. :)

**Comment by panesofglass** [comment]
I'll see if I can publish a new 2.0.202 that backs up the dependencies.

**Comment by panesofglass** [comment]
Bizarre. The 2.0.201 tag is pointing at a different commit than the one I thought I tagged. I appear to have made a significant mistake.

**Comment by panesofglass** [comment]
Okay, this appears to be resolved. @SimonGustavsson, please update your Freya to 2.0.202 and let us know. I untagged 2.0.201 and removed it from the NuGet listings. 2.0.202 should show up and 2.0.201 should be hidden soon. Thank you very much for reporting this error!

**Comment by SimonGustavsson** [comment]
Ah, how unfortunate that I updated my project to not use the "obsolete" stuff before you got back to me :-)
Thanks for the speedy response though! I'm liking the project a lot, keep up the good work!

**Comment by kolektiv** [comment]
Well, if you don't upgrade, 3.0 will catch up with you :) Happy to hear
you're liking it, any feedback (and we mean any!) listened to...

A.

**Comment by SimonGustavsson** [comment]
Hi again :) 
I was experiencing some oddities with routers, so I figured I might try upgrading to 2.0.202.
However, after upgrading I'm experiencing multiple errors saying `The module/namespace 'Aether' from compilation unit 'Aether' did not contain the namespace, module or type 'PLens`2'`.
You wouldn't happen to know what that's about, would you? I'm assuming I'm doing something weird. :)

**Comment by kolektiv** [comment]
I have a sneaking suspicion that I do, yes. I think we need a new release
of Freya 2.x with version restrictions on some of the dependencies. At the
moment it's probably open ended, and that's now going to be picking up new
releases of Aether, etc. That's a problem on the Freya side though.
@panesofglass is that something you could push out?

I'm not sure how you pushed the previous 2.x point release.

There might be a quick workaround possible if you're using Paket for
package management? If you are, add

Aether ~> 7
Chiron ~> 5
Hekate ~> 1

to your paket.dependencies. That should, I think, restrict the global
versions of those to compatible ones until Freya restricts them correctly.

Sorry, we need to nail the dependencies down properly on Freya. They're
fine now for 3.x but 2.x was not sufficiently restricted.

**Comment by panesofglass** [comment]
@SimonGustavsson did you happen to delete your packages folder before updating to 2.0.202?

**Comment by panesofglass** [comment]
oic, yes, @kolektiv is correct. Let me make another change and push.

**Comment by panesofglass** [comment]
@SimonGustavsson I think this is now fixed. Please re-open if you continue to experience problems.

**Comment by kolektiv** [comment]
The paket.dependencies file https://github.com/freya-fs/freya/blob/master/paket.dependencies looks slightly odd at the moment, duplicated/clashing versions? Not sure what's happened there? Maybe a cross version merge... I think maybe we should split off a 2.x branch and make specific builds from that if possible - it might be easier :)

**Comment by kolektiv** [comment]
(Oh, should note that the actual dependencies in the released packages are correct though, so it's only a minor point at the moment! :)
