### ISSUE TITLE
Please make Freya.Machine.Extensions.Http.Operations public

### ISSUE THREAD

**Issue by mexx** [freya-fs/freya#151]
I have a special use case, where I don't need the whole power of `Freya.Machine`, but have to make authorization.
Currently the operations like `unauthorized` are private.
It would be great when those were accessible as building blocks, especially as they mostly do not require anything from `Freya.Machine`.

**Comment by kolektiv** [comment]
Oh that's interesting, I hadn't thought of them being useful in that way. I don't see why not, I'll look at making them public in 3.0 which should be very soon.

The underlying structure of how machines work will be changing in 4.0 one day (although not really visibly to the Freya user) and the operations were likely to disappear as distinct things - but you've made me think it might be useful to keep them around and make them more obviously accessible/usable. Thanks, that's a good thought, I'll try and make them open as they are for 3.0 and then see if I can make them more accessible/decoupled for 4.0 too (one day!)

Thanks!
