### ISSUE TITLE
`SystemNetHttpAdapter` needs to configure `HttpRequestContext`

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#16]
See [notes on `HttpRequestContext`](http://www.strathweb.com/2013/08/asp-net-web-api-2-and-httprequestcontext/). This is especially important to provide properties such as the `IPrincipal` used in the request.

**Comment by kolektiv** [comment]
Can we close this now as the NetHttpAdapter has gone for the time being @panesofglass ?

**Comment by panesofglass** [comment]
Yes, let's close this and remove the adapter project. I don't think it makes sense any longer.
