### ISSUE TITLE
Freya.Router can't handle requests with %5D in path

### ISSUE THREAD

**Issue by mexx** [freya-fs/freya#173]
Given a simple router like
```fsharp
let router = freyaRouter {
    route All "/{id}" handler }
```
when requested with `/some%5Dtext` the route is not matched.

The problem arises from the fact that the `owin.RequestPath` is provided as percent-decoded value as required per [OWIN v1.0 Spec 5.5 Percent-encoding](http://owin.org/html/spec/owin-1.0.html#5-5-percent-encoding).

The `UriTemplatePart` matching algorithm expects the path to be encoded.

**Comment by kolektiv** [comment]
Hmmm. That's... annoying on the part of OWIN! I'm not sure what the best approach will be, other than finding an alternative source of the original path (non-spec compliant, so probably not) or - and I suspect this might be the only way - re-encoding the path before matching on it. Which isn't really ideal, but i'm not sure there's much else in terms of options. What do you reckon? You might have a better idea than mine, in which case I'll go for it!

**Comment by mexx** [comment]
For me there are two ways, re-encoding or loosen the matching parser to accept also already decoded input. Both options should lead to success. I see freya-fs/arachne#34 as somehow related to this issue.

For now re-encoding looks more correct to me. I think we should provide `Request.pathEncoded_` and `Request.pathBaseEncoded_` lenses and use it in the search for a matching route.
