### ISSUE TITLE
Is it "ok" to put stuff into the environment dictionary

### ISSUE THREAD

**Issue by Vidarls** [freya-fs/freya#183]
I find myself passing much of the same stuff into each machine config. Makes a lot of noise and ceremony.

Is it ok / within best practice / not frowned upon to put stuff into the owin / freya enviornment dictionary for "global request scope" access?

If so, what is it ok to put in there, and when to do it to ensure it is there when I need it?

If not, any pointers on how to handle stuff needed everywhere without adding an extra argument to every function (and parent function) where it is needed?

**Comment by kolektiv** [comment]
The simple answer is yes, it's reasonable to use the environment for request scope (in my opinion at least). Controlling how that's done is slightly trickier, and Freya has something to help there. The function `Freya.memo` will take any `Freya<'a>` function and return a new `Freya<'a>` function - but which will only run once per request, and the result will be stored in the environment (or nearby!).

This means that if you have a function that, say, gets a resource given an id, you can simply wrap that function in `Freya.memo` and then call it wherever you like - it'll only ever run once, the first time it's called. This can make the programming model simpler and more declarative.

**Comment by Vidarls** [comment]
Found that I did not really like how it affected composability to put config inside memos, so found a different way of organizing my code. Now got a much better feel for it :smile: Thanx for input though.

**Comment by kolektiv** [comment]
Fair enough :smile: Memos work well for some things, but not all!
