### ISSUE TITLE
CORS support in the Machine graph

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#26]

**Comment by panesofglass** [comment]
I just tried again with FireFox. CORS doesn't work there, either. I can only get it to work in Chrome.

**Comment by kolektiv** [comment]
Hmmm, that's definitely weird then, I'm going to look in to that before merging anything else in!

**Comment by kolektiv** [comment]
Hmmm, we'll definitely need to come up with some standard testing for this! I just tried it in my Windows VM with a newly installed Firefox, pointing TodoBackend at localhost:7000 and it worked without a hitch. Which is odd... What's the setup you're testing?

**Comment by kolektiv** [comment]
Closing for now, can reopen if anything new pops up.
