### ISSUE TITLE
OWIN Integration

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#28]
Support to / from `OwinAppFunc` and `OwinMidFunc`. Primary use cases are to leverage existing tools such as Glimpse and security middleware.

**Comment by panesofglass** [comment]
Glimpse integration into OWIN relies on either `IAppBuilder` magic or explicit weaving of Glimpse middleware around each OWIN middleware. If you (@kolektiv) can document how `Inspector`s work, I can work with @nikmd23 on any remaining issues. I showed him the Graph you were able to generate, but I don't understand `Inspector`s enough to work out any potential issues.

**Comment by kolektiv** [comment]
Ah interesting, I'd come to the conclusion with Glimpse that it did seem a bit tied to asp.net, and working with more generic low level approaches seemed to require quite a lot of grunt work. It seems I was probably half right! I'm working on some docs, I'll make the inspector one of them, although it's quite early stages, and it's very much open for debate as well!

**Comment by panesofglass** [comment]
You would need to look at one of the Glimpse branches in version 2.0 that provides support for OWIN. The original versions of Glimpse were indeed tied to ASP.NET.

**Comment by kolektiv** [comment]
So, I'm getting my head around this, however, I've realised I don't quite fully understand the specification/intended usages of OWIN MidFuncs, etc. are they essentially double tap middleware? Is there a specification for these somewhere and some examples of how they're implemented and actually used?

**Comment by panesofglass** [comment]
@kolektiv I can't find @serialseb's draft spec for `MidFunc`. The basic concept is that it follows a russian doll model of composition. A `MidFunc` accepts an `AppFunc` and produces a new `AppFunc`. The `MidFunc` may take some actions before and/or after` executing the provided `AppFunc`. The `MidFunc` may also decide to halt progress and complete the `Task` itself, never calling the provided `AppFunc`, a good example of which is used in security middleware that prevents further execution in the pipeline.

**Comment by serialseb** [comment]
https://github.com/openrasta/owin.spec/blob/master/spec/middleware-1.0.0-draft.1.md

**Comment by panesofglass** [comment]
Thanks, @serialseb!

**Comment by kolektiv** [comment]
Thanks @serialseb - I get the approach now. The middleware approach is what I would usually refer to as "double tap" as opposed to our current pipeline model which is basically single tap. I wonder if we should consider changing the pipeline model to make it double tap in some way? Would be quite easy to define an inductive definition for a pipeline like that which would be simple to program against, and if we were to change the pipeline composition operator to be right-associative it would be quite a simple build process to create them.

What do you think @panesofglass ? Is it worth considering extending our pipeline model a bit?

**Comment by panesofglass** [comment]
@kolektiv, I'm not sure I follow, but I'm happy to try both approaches: changing the pipeline model and attempting to continue my experiment in #59.

**Comment by panesofglass** [comment]
@kolektiv, for what it's worth, I have started to prefer the single-tap approach.

**Comment by kolektiv** [comment]
I guess I'm essentially thinking of changes to the pipeline model which would make it double-tap. As much as anything because, if our pipeline isn't double-tap, I'm not sure how we can properly support owin middleware that is. Like you, in some ways I prefer the simplicity of single-tap, but it doesn't seem to be the way that OWIN is going? I might have a quick play with the pipeline model too. I have the initial feeling that supporting that model wouldn't be too difficult, just a feeling of "is this the right thing?". 

Can you think of ways of supporting OWIN middleware in pipelines which don't require us to go double-tap? My brain might be a bit slow at the moment, but I'm not sure I can...

**Comment by panesofglass** [comment]
> Can you think of ways of supporting OWIN middleware in pipelines which don't require us to go double-tap? My brain might be a bit slow at the moment, but I'm not sure I can...

Yep, that's what I'm working on in the PR.

**Comment by kolektiv** [comment]
In that case, awesome :) I'll look forward to seeing that!
