### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by tpetricek** [freya-fs/freya#35]
I had a quick look at the tutorial, but it looks like it needs a bit of work: https://github.com/freya-fs/freya/blob/master/docs/content/tutorial.fsx :-)

**Comment by kolektiv** [comment]
Definitely still early days but I've started collecting the documentation i'm writing (stubbed in most cases) over at https://github.com/freya-fs/freya.documentation.

**Comment by panesofglass** [comment]
Couldn't all this go in the `docs` folder of this project to aid discoverability?

**Comment by kolektiv** [comment]
At the moment I'm experimenting with it being pulled in to other
repositories as part of a documentation site build etc. In the meantime we
could perhaps submodule it in to docs for now, that way it'll at least show
up while people are browsing GitHub? I'm not sure that the fsformatting
approach is the right one for more general help files etc. but will see
where it ends up...

**Comment by forki** [comment]
could you add a link to the current docs in the readme?

**Comment by panesofglass** [comment]
Yes, good idea. Links added to README

**Comment by panesofglass** [comment]
This was superseded by #94.
