### ISSUE TITLE
Document generation needs to be added to the build

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#38]
Should perhaps consider our flows around this, and whether we want it built in the same cadence as releases to master, etc.
Should we consider separate documentation for master (stable, post 1.0?) and develop? Worth a chat.

**Comment by forki** [comment]
versioned documentation are a general issue with the current FSharp.Formatting "ProjectScaffold" process.

**Comment by kolektiv** [comment]
See #71
