### ISSUE TITLE
Build publishing NuGet packages

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#39]
Not sure if NuGet packages are actually being published. Perhaps @panesofglass to check the keys, etc. on AppVeyor?

**Comment by panesofglass** [comment]
I set up a deployment, but it's not run as part of the build. If subsequent builds don't correctly update the version, the build fails for failure to publish.

**Comment by kolektiv** [comment]
Ah yes, that old chestnut! Happy to leave it like this for now then, manually pushing releases probably isn't too bad an idea for now. I'll close this.
