### ISSUE TITLE
Move to Freya organisational accounts for CI?

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#40]
At the moment the CI on AppVeyor and Travis is under @panesofglass accounts. We should probably look to move these to freya accounts for maintainability/admin scaling perhaps.

**Comment by panesofglass** [comment]
Done! Check AppVeyor. You may need to sign out to see the freyafs org in AppVeyor. Please reopen if you have problems.

**Comment by kolektiv** [comment]
Fantastic! Works for me, that's awesome :) Thanks!
