### ISSUE TITLE
Consider the creation of Freya metapackage

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#41]
For those users (especially new users) who wish to simply grab everything they'll need (and especially when doing things like following along with tutorials), perhaps we could create a package simply called "Freya" - or something suitably descriptive alternatively - which would bring in all of the stable mainstream libraries in the stack (excluding anything published under experimental, etc.)

**Comment by panesofglass** [comment]
I like it. :+1:

**Comment by kolektiv** [comment]
I'll tweak the build to do so tomorrow.

**Comment by kolektiv** [comment]
This is now done and pushed to the develop branch, and will get pulled in to master next time we aim for a fuller release.
