### ISSUE TITLE
Consider publishing of experimental parts of the stack under a specific namespace

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#42]
...or if a namespace/assembly name shift is deemed too intrusive, perhaps some other approach. I'm not sure that simply prerelease packages will be enough, as I'd like to have regularly pushed prerelease packages from the develop branch, and master representing stable. But I'm open to more sensible suggestions... @panesofglass ?

**Comment by panesofglass** [comment]
Well, I'm at the point where I would like to remove the `System.Net.Http` adapter. I think it detracts from what Freya offers. If everything else is plugins, we probably don't need an additional namespace.

**Comment by kolektiv** [comment]
OK that's fair enough - i'll remove it while I'm fiddling with things tomorrow. It's not like it's unrecoverable, it can always be resurrected! I'll close this when that's done. I'll open a new issue with more focus on building releases for develop when I've given it some thought.

**Comment by kolektiv** [comment]
This has been removed in the latest changes to develop, and will be merged in to master next time we release in that way.

**Comment by panesofglass** [comment]
I already removed it from master, I think.
