### ISSUE TITLE
Logo!

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#43]

**Comment by forki** [comment]
Maybe @sergey-tihon can help here!?

**Comment by panesofglass** [comment]
We are already iterating on one. Thanks, though!

**Comment by sergey-tihon** [comment]
Something like this ;)
![image](https://cloud.githubusercontent.com/assets/1197905/5723634/60118568-9b56-11e4-8322-0fd7f1022769.png)
from http://www.mylifetime.com/shows/witches-of-east-end/cast/jenna-dewan-tatum

**Comment by panesofglass** [comment]
@mathias-brandewinder wanted

![Freya with her cat-drawn carriage](http://www.viking-mythology.com/img/Freya_rode_in_a_chariot_pulled_by_two_black_or_gray_cats.jpg)

from http://www.viking-mythology.com

**Comment by panesofglass** [comment]
Some progress appears below:

![screen shot 2014-12-04 at 11 39 09 pm](https://cloud.githubusercontent.com/assets/8803/5723826/bbec46c4-9b0c-11e4-93cd-7390ed2ac84e.png)
![screen shot 2014-12-04 at 11 47 54 pm](https://cloud.githubusercontent.com/assets/8803/5723829/c1e0eb20-9b0c-11e4-9511-022a15b76bd2.png)
![screen shot 2014-12-11 at 8 35 54 am](https://cloud.githubusercontent.com/assets/8803/5723847/db4a7144-9b0c-11e4-853e-34fa91224817.png)

**Comment by forki** [comment]
omg that's aweesome!

**Comment by sergey-tihon** [comment]
This one looks interesting!
![image](https://cloud.githubusercontent.com/assets/1197905/5723872/7b29a4aa-9b58-11e4-9fb9-16fd062c5752.png)

**Comment by panesofglass** [comment]
@goodnightjj from Tachyus volunteered and has been helping. We slowed down over the holidays, but I think we are close!

**Comment by panesofglass** [comment]
Logo may be found at http://1drv.ms/1zMXGvH

![logo](http://1drv.ms/1zMXGvH)

**Comment by sergey-tihon** [comment]
:+1:

**Comment by nicholas-peterson** [comment]
While the logo above is excellent, I wonder if anyone considered using the rune 'Fehu', which would be used to spell Freya. It also makes the relation to F# more explicit. http://commons.wikimedia.org/wiki/File:Runic_letter_fehu.svg

**Comment by panesofglass** [comment]
@nicholas-peterson, we did not even think of it. Thank you for the suggestion!

**Comment by haf** [comment]
Did you intentionally make a cat-woman-logo?
![screen shot 2015-03-10 at 23 53 50](https://cloud.githubusercontent.com/assets/193115/6587139/c5ff3f4a-c780-11e4-8c77-518da148fa3e.png)

**Comment by panesofglass** [comment]
@haf, yes indeed. The cats pull Freyja's chariot. Glad you like it!
