### ISSUE TITLE
Roar-like Hypermedia support

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#44]
https://github.com/apotonick/roar

**Comment by kolektiv** [comment]
I'm thinking that we might be able to look at this in terms of graph extension - see #46...

**Comment by panesofglass** [comment]
We could use https://github.com/DotNetHypermedia/DotNetHypermedia

**Comment by kolektiv** [comment]
Definitely interesting. I'm hoping that the modular machine work might make it quite easy to integrate things like this...

**Comment by panesofglass** [comment]
Tracking in #46
