### ISSUE TITLE
Composability/modularisation of the machine graph

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#46]
I've started an experiment around making the machine graph much more flexible to the end user. That's coming along nicely, so this is a placeholder for that, especially to be referenced from issues where modification and extension of the graph may support extra new feature layers.

**Comment by kolektiv** [comment]
As an update, this work is now happening on my develop branch at https://github.com/kolektiv/freya/tree/develop and I'm quite pleased with how it's going. As an example of how this works, see the Freya.Machine.Console (a temporary harness), where the first configuration of the defaults specifies a graph to use - or more accurately, an extension to the existing graph.

See Freya.Machine.Http/Extension.fs and related files to get a feel for how graphs will now be defined...

Opinion welcome, especially @panesofglass - thinking of things like hypermedia, etc, it should be possible to write an extension which would (for example) replace the default handlers (and add computation expression syntax) so that all resources you returned were passed back through a hypermedia formatter. 

This would just be modification to a graph, and would then be seamlessly supported when people used "handleOkHAL" for example, as opposed to "handleOk". The details are obviously still to be explored, but it seems as if it would certainly be possible to achieve some quite cool things.

I'm not aware of any other framework out there which supports doing anything quite like this...

**Comment by panesofglass** [comment]
Copying @glennblock and @darrelmiller for input, as well.

**Comment by panesofglass** [comment]
@glennblock in particular, I'm looking at how https://github.com/DotNetHypermedia/DotNetHypermedia might fit into this implementation.

@kolektiv, have you documented this yet? I found https://github.com/kolektiv/freya/blob/develop/src/Freya.Machine/Types.fs#L108-125, but I don't quite know what to do with that at the moment.

**Comment by kolektiv** [comment]
No it's very early indeed at the moment, I haven't ported the graph back over to the new Freya.Machine from Freya.Machine.Old (yes, great use of version control!), but if you look at https://github.com/kolektiv/freya/blob/develop/src/Freya.Machine.Http/System.fs you'll see a tiny example of the graph being built up (non-operator syntax is available!) That means that any new assembly can expose an extension(s) as part of a freyaMachine computation expression (the new "using" syntax, as seen at https://github.com/kolektiv/freya/blob/develop/src/Freya.Machine.Console/Program.fs#L9) and build/modify the underlying machine graph at reification time. 

Those modifications have a level of safety built in, with extensions a) specifying dependencies, and being validated in to a dependent order before modification of the graph and b) the individual graph operations perform some precondition type checking before succeeding. More can be done around that later too.

This means that you can choose whether to use things like CORS (if you don't want it, simply don't have it in the graph, it'll be a separate extension now), and also to enable new extensions to the processing graph to do extra work around hypermedia or other specific features which you might like to have.

For example, you might write a graph extension which does something like:

Remove the edge from to_content (see https://raw.githubusercontent.com/for-GET/http-decision-diagram/master/httpdd.png) to handleOk.
Remove the node handleOk.
Add a new node handleHypermediaOk.
Add an edge from to_content to handleHypermediaOk.
Add new syntax to freyaMachine to accept a new and more specific function to be run on handleHypermediaOk (perhaps a function that must return some structural type encoding relationships and a resource, rather than a simple byte [] representation of the resource) which will be handled by the new handleHypermediaOk node in the graph.

Now freyaMachine seamlessly supports a hypermedia resource, while keeping all of the other logic and making that available to extensions where appropriate.

**Comment by panesofglass** [comment]
I definitely like the direction. I'm impressed you are able to add in those validations, as well. Great job!

With respect to `handleHypermediaOk`, I think it will be interesting to see how to weave in content negotiation so that multiple representation formats can be added in with rules governing how to select the appropriate representation. Would you handle this using a sub-graph to select the appropriate formatter and then roll that back up to return the result using that representation?

(I'm still working my way up the stack from Freya.Core, so apologies if I ask what appear to be overly simple questions.)

**Comment by kolektiv** [comment]
I think the question of exactly how best to implement things with graph modifications is still open - one of the things I'm hoping to discover with some experimentation as part of #49. It is essentially likely to be something like splicing a sub-graph in to the overall graph, or replacing/wrapping the existing node in  some way. I think it's going to be quite interesting to explore the different approaches for that.

No apologies needed - everything so far has resulted in an improvement in some form or other, I'm happy to get questions!

**Comment by panesofglass** [comment]
@kolektiv do we have the functions necessary to help a machine select the correct representation yet?

**Comment by panesofglass** [comment]
Several of the attendees of my talk (well, for sure one of them) thought the idea of composing the graph sounded interesting. Things to consider:

* If a goal is to drop people into the pit of success, how do we do that if we don't push the graph on them? How do we prevent them from doing bad things?
* How do we handle potential graph collisions?
  * Will graphs always be separate paths, and if so, how do you decide between each?
  * If graphs are merged, how do you pick a winner where graphs provide similar or the same "name" or definition?
* Will we provide defaults to help people get started? Will we allow users to modify existing graphs, or must they create their own version of the `http` graph, for example?
* Will `Recorder`s be woven into custom graphs by default, or will graph creators need (or want) to have more control over recorded points?
* Can we provide a way to toggle `Recorder` granularity if we bake that into the graph components?

**Comment by panesofglass** [comment]
Missed another question:

* How do you toggle available builder functions?

For this one, I think the answer is that the `using` leverages type extensions to add additional builder members that then provide either additional overloads to the builder. I'm not sure, though, how you control that using the `using` expression since type extensions are typically added by opening the relevant library. Also, if you open the library, how do you prevent those extensions from appearing as valid if you aren't also using the graph module with a `using`?

**Comment by kolektiv** [comment]
I'm updating this as I realise I didn't do so before, but having worked with the graph work now to the point where it's usable, I think I can...

* I think that making it as easy as possible (as I think it currently is) is probably about all we can do - plus good docs. Possibly also some warning messages if you ever try to compile a graph which is simply Start -> Finish!
* Graph collisions is tricky. The extension system allows you to specify dependencies, so you should at least be sure that the graph you're modifying is "at least" X. However, there may have been modifications you don't know about, so your modifications may leave the graph in an invalid state. To some extent I'm not sure this will be a big problem in practice. I don't think it'll be common to be using "lots" of extensions at once, probably only 2-3, and most likely ones provided by the Freya project. However, we can also mitigate potential problems by graph verification, and validating a graph as being in a correct state before allowing it to be used at runtime. The switch to Hekate for graphs will make this much easier.
* Defaults certainly, and they can modify that by providing an extension - an extension is always simply a modification of the existing graph.
* Recorder is at the machine level, and so will apply to the graph no matter how it's modified. In terms of giving people more control over recording - not as standard, but they could write their own inspector using the recorder + inspector APIs if they wanted specific data collected on their processes. That goes for anything on Freya, not just Machine based work of course.
* Not sure - interesting question, will chat about that at some point!

And the missed one:

* This is tricky. As you say, opening the module makes the syntax available, even if you're not really using it. I've tried to make it so it wouldn't make any sense to open that module unless you were going to use the functionality, but it's a potential trap if people do "unexpected" things. Some really good debugging and verification steps at early runtime may help, but the granularity of extending computation expression syntax isn't really there (and there's no to "remove" syntax - understandable really!) It's pretty much pushing the limits of sane usage as it is :)
