### ISSUE TITLE
Implement Run in Computation Expressions

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#48]
I think we could embed the `reify*` functions into the computation expressions by implementing `.Run`. IIRC, `.Run` is appended to the end of a computation and so executes at the very end. That might not be quite the same as what you show in the TodoBackend sample, but I think it would work and clean up that bit of noise in the sample. Thoughts?

**Comment by panesofglass** [comment]
This is just a suggestion. As @tpetricek notes [here](http://stackoverflow.com/questions/3937264/run-method-in-computation-expressions), implementing `.Run` could break composition (unless something has changed).

**Comment by kolektiv** [comment]
Yeah, it seems very tempting but sadly in our case it would break composition (which is a really nice aspect of freyaMachine/freyaRouter especially, using the "including" syntax). I'd love to find a way of at least avoiding a family of reify* functions, but I can't think of one without having to create an assembly which knows far too much about everything and sits at the wrong logical level (for example, creating a statically inferred reify method which would accept either builder type).

At the moment I think we're rather stuck with it, unless someone can come up with a good plan! Reification is very much a process at the end of x amount of composition, etc. so I'm not sure we can choose when to automate it.

Do you want to leave this open as a potential placeholder for a "keep thinking about better alternatives" discussion?

**Comment by panesofglass** [comment]
Yes, let's leave it open if you don't mind. Another point on the `reify*` naming, could this be renamed to something like `Machine.toPipeline` (assuming we drop the `Freya` prefix). That's the point of the `reify*` functions, isn't it? Many to whom I have shown `reify*` get a bit spooked. If the goal is to convert a computation to the more general `Pipeline`, I think `toPipeline` might be clearer, less spooky, and also follow some the F# conventions a bit better.

Or have I misunderstood `reify*` functions? :)

**Comment by kolektiv** [comment]
No I think you've understood them perfectly, and something like Machine.toPipeline makes sense, along with Router.toPipeline. It is undeniably better than the current, so I'll change it :)
