### ISSUE TITLE
vNext support

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#50]
This is really here as a reminder to make sure that this stuff works seamlessly with whatever stuff vNext is about to throw down the pipe. I don't know what changes are relevant yet, and I'd like to find out, along with potentially supporting a wrapper/adapter project if we find that we need to support some new and "interesting" abstraction (Builder.ofFreya or something maybe, I don't know...)

Maybe @panesofglass has been keeping track of vNext more than me and could give me a 5 minute crash course at some point :)

**Comment by panesofglass** [comment]
I have not been tracking it as closely as I'd like. I know they have support for OWIN apps, and @Alxandr has been tracking and building support [here](https://github.com/YoloDev/YoloDev.FSharp.AspNet). I saw recently that @KevinRansom was working on .NET Core support for F#, as well.

**Comment by kolektiv** [comment]
Hmmm. Things seem to be more around providing support for F# in ASP.NET, which, in the nicest possible way, doesn't interest me too much :) Maybe we don't need to worry too much and we can sit lower in the stack?

I think what I'm most worried about is middleware reusability - I want to make sure that using middleware in Freya will be easy, and that might be awkward if MS have wrapped it in some new typed abstraction (I saw the awful sounding MidFunc somewhere today, hopefully that was a dream).

**Comment by panesofglass** [comment]
@kolektiv I think we can just leverage the OWIN support `app.UseOwin()` and hook into that. The .NET Core support could be useful there.

**Comment by panesofglass** [comment]
As to `MidFunc`, MS isn't doing anything with the concept of middleware, at least not true middleware. Most of their concerns are building up applications by leveraging a `404` fall through. Security and other components, like those from Thinktecture, should support the `MidFunc` or be convertible to `MidFunc`.

**Comment by panesofglass** [comment]
`MidFunc` is `Func<AppFunc, AppFunc>`, and yes, the nicknames are pretty bad.

**Comment by panesofglass** [comment]
FWIW, I would expect our current implementation to run on .NET Core so long as dependencies, e.g. FParsec and Aether do so. I'm a little concerned about FParsec making the jump.

**Comment by kolektiv** [comment]
I'm pretty confident in Aether (I can't think of anything even vaguely outré that I do in there. FParsec, I'm not too sure. That might be a bit of a stretch (in fact it might be worth testing that at some point - i'll grab the code and try!)

**Comment by KevinRansom** [comment]
I have started a fork on CodePlex for enabling F# support for the NetCore platform, currently it can be a netcore fsharpcore, which is clearly the most necessary first step.

I will port the fork to GitHub now that we have moved visualfsharp to there and get back on it.  Clearly though this will need people to look at it and try it out for a variety of projects.  Perhaps once I have created a couple of templates, we can encourage people to test it out.


Kevin

**Comment by panesofglass** [comment]
I don't think there's anything to do here. ASP.NET 5 supports OWIN, so the only thing we need to do is ensure we will fit in .NET Core, which we should since we take virtually no dependencies. The only exception of which I'm slightly afraid is FParsec, for which we would need a custom build, I think. It's possible that @devshorts' [ParsecClone](https://github.com/devshorts/ParsecClone) might be a bit easier to get working on .NET Core, though I'm not certain. In any case, I think we can close this until .NET Core support is available and we can actually test that something breaks.

Closing for now.
