### ISSUE TITLE
Resource naming in machines

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#51]
Given URIs are just names for resources, and resources are defined as machines, does it make sense to apply the URI as a parameter to the machine definition rather than lean on a separate routing mechanism? This would provide a similar mechanism to attribute routing in the ASP.NET MVC.

The reason I ask is that, in discussing Freya with a friend this morning, it struck me that we are defining resources as machines but not giving them identifiers when creating them. Perhaps it is better to assign the identifier later, but I wanted to raise the question. I'm not opposed to either solution.

**Comment by kolektiv** [comment]
Hmmm, it's an interesting one. At the moment I quite like the fact that they're separate. The router has intrinsic value as a router of "any pipeline" and resources are just pipelines once reified (naming changed in my fork already!). Also a resource may exist at multiple locations quite feasibly, so it's not necessarily something which is strictly bound. I'm hoping that the router will gain other things to route over time - alternative things which compile to pipelines - a freya version of templated pages perhaps, or any number of other things.

Worth keeping an eye, but not sure I'd change it at this point.

**Comment by panesofglass** [comment]
Agreed; again just posed it for discussion.
