### ISSUE TITLE
Simple File Server returns 406 rather than 404

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#55]
The simple file server demo highlighted a bug in the machine/routing implementation. The path accepts a parameter representing the file name. When I ran the server and entered a valid file, I received the file in the response. However, if I used a non-existing file, I received a 406, indicating that the response could not be formatted properly. This should have resulted in a 404.

Actual status code: 406
Expected status code: 404

Repro:

1. Add a known file with a known file extension and content type
2. Verify you can retrieve the file with a `200 OK`
3. Request another file with the same extension and content type
4. Receive a `406 Not Acceptable`

**Comment by kolektiv** [comment]
Indeed, I'll take a look at that...

**Comment by panesofglass** [comment]
@kolektiv, I think you fixed this, didn't you? If so, would you mind closing?

**Comment by kolektiv** [comment]
Yeah this can be closed as it can be fixed fairly easily in the simple file server.
