### ISSUE TITLE
Investigate use of the update monad for tracking modifications to Environment

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#6]
Now that we have @kolektiv's `OwinMonad`, which uses Lenses, is this needed or worth the effort?

See http://tomasp.net/blog/2014/update-monads/index.html and http://www.infoq.com/news/2014/03/ddd-cqrs-fsharp

Concerns:
* will this break use with other OWIN middleware components?

Pros:
* tracing/logging built-in to the pipeline!
* ability to write components that can adapt to previous behaviors before the behaviors are executed

**Comment by kolektiv** [comment]
Tempted to close this, if we want to revisit at some point we can open a new chain I think. What do you reckon @panesofglass ?

**Comment by kolektiv** [comment]
Closing this for now as it's not really suited to the current direction. May be worth revisiting at some point but we can create a new issue if it's relevant.

**Comment by panesofglass** [comment]
Works for me. :)
