### ISSUE TITLE
Support HTTP PATCH (RFC 5789) in the graph

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#61]
What do you think about supporting [HTTP PATCH](http://tools.ietf.org/html/rfc5789) in the graph? Would this be part of the defaults or an extension?

**Comment by kolektiv** [comment]
I think this is probably something which would fit as an extension in some form. I'm not totally sure exactly what form yet! I want to do some work on a new and more extensible baseline graph at some point, which will provide a more extension friendly topology, and pare the default graph back to the core RFC 7230-7235 definition of HTTP. From that point, things like CORS, PATCH support (as it's not core HTTP in that sense) and extra functionality would be expected to be provided by graph extensions.

**Comment by panesofglass** [comment]
Sounds good to me.

**Comment by panesofglass** [comment]
Covered by #54
