### ISSUE TITLE
Split Types.* Libraries to separate project?

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#63]
I find that I work on other libraries which could really use some of the types in the Freya.Types.* libraries. I'm not sure that I want them to have a dependency on part of a web stack though. Would the types be better off in a separate project (perhaps under a different name?) to make them more accessible to projects outside of the Freya web stack?

Perhaps if they remained Freya.Types (as a top level repo) that would still align with a Freya (organisation) being an organisation for better web programming, and one of the sets of libraries it provides is a web-specific set of types...

I'm not sure how I feel about this! How about you, @panesofglass ?

Any thoughts/opinions welcome!

**Comment by panesofglass** [comment]
Is NuGet packaging not sufficient?

**Comment by kolektiv** [comment]
It probably is, it's more of a thought experiment. Would a standalone types library encourage re-use more than them "seeming" like a part of a big stack... In my case it's probably not an issue really (except for questions of subjective taste), just a consideration.

Anecdatally (sic) one or two people did seem to like the idea of a good library/library set of web types...

**Comment by panesofglass** [comment]
Would you somehow remove the Freya dependency? If so, I could see them being split out and useful, though I like retaining the name. My hesitancy comes from having done this on WebApiContrib, where I thought by pulling everything out, I would see more people contribute. That was not the case. Instead, I now have to manage a large number of builds and repos. :( I still need to resolve that build issue and pass the lot to someone else.

**Comment by kolektiv** [comment]
Well, the Types library actually has no Freya dependency! Freya.Types +
Freya.Types.* is actually a self contained set - they have no dependency on
Freya.Core or other bits... So in theory they could be a self contained set
of libraries.

Difficult one, I'm not too sure either!

**Comment by panesofglass** [comment]
@kolektiv, that's excellent! We should keep it that way. Not sure if you caught the update to my previous comment. I added the following:

> All that to say, let's fix the dependencies so that it's possible but wait to make the change until we have evidence that moving these projects out is going to save us work rather than just create new work.

**Comment by kolektiv** [comment]
Yeah that's fair enough, let's keep an eye on it for a bit... (The place it came up was Chiron.Schema, when I really wanted an AbsoluteUri type...)

**Comment by kolektiv** [comment]
See #66
