### ISSUE TITLE
Separate Freya.Types into a new library: Arachne

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#66]
I've experimentally (in a branch of my fork) pulled the types out of Freya.Types[.\*] and in to a new set of libraries called Arachne[.*] These libraries contain solely F# idiomatic types and parsers for web related programming, without tying the types to any specific web framework implementation. They can be used completely independently, wherever you might need special-purpose web based types.

Freya.Types[.\*] is gone, and is replaced by Freya.Typed.* (currently Http and Http.Cors). These don't contain types themselves, but provide *typed* access to the OWIN state data in Freya through lenses (the standard way of working with data in Freya), exposing the underlying data as Arachne types transparently.

All of the places which previously used the Freya.Types[.*] types and lenses have been converted to the new approach.

Opinions welcome... @panesofglass / @mavnn / @kjnilsson ?

Edit: Yeah, I could make this easier by including the branch it's in couldn't I...

https://github.com/kolektiv/freya/tree/feature/arachne

**Comment by panesofglass** [comment]
@darrelmiller and @serialseb, would you be interested in us breaking out the types and parsers into a separate set of libraries? @kolektiv put a lot of effort into parsing correctly based on the RFCs. The types are currently far more friendly towards F#, but we can probably work with you to make them more easily consumed from C#. I ask b/c Darrel mentioned he and Seb are both working on parsers.

**Comment by serialseb** [comment]
If you get them usable from c# that'd be good yes. My libs are mostly a validator based on a custom abnf engine i wrote for fun :)

**Comment by panesofglass** [comment]
@kolektiv let's move forward with this task, keeping the project(s) under freya-fs. What do you think? If nothing else, it may make it simpler for @suaveio to consume. See https://github.com/SuaveIO/suave/issues/153.

What do you think about switching to @devshorts' ParsecClone rather than FParsec, as requested by @haf?

**Comment by mausch** [comment]
The [helpers I wrote in FSharpx](https://github.com/fsprojects/FSharpx.Extras/blob/master/src/FSharpx.Extras/CSharpCompat.fs) are meant for C# programs that want to call into F# code that exposes curried functions / options / choices / F# async / F# lists / etc.
If you don't mind having that in C# (I don't, hence these helpers), then these helpers should be useful.
Otherwise it's best to model the C# API in the F# codebase.

**Comment by kolektiv** [comment]
Yeah I think it's good to take this forward. Do we want to try and pull them in to a separate namespace? Might make things clearer then what has a Freya dependency and what does not.

On the FParsec/ParsecClone side of things, I'm certainly open to that. I don't know how much of a change that would be, but I'll take a look at it... Maybe a quick experimental branch for just that.

In terms of C# usage, i'm not sure how much and what kind of work we can do. All of the types are currently union types, and I can't remember what those are like from C# (I'm assuming not lovely). There are not many actual functions involved here except for the static and instance members on the types, so that probably doesn't require too much of a change (perhaps changing the Try* methods to the standard .NET form in some sense).

Like @mausch I don't really mind too much about the helpers because I don't write much/any C#, but I suspect for wider adoption, extra dependencies like that might be an issue. I guess from @serialseb and @darrelmiller it would be good to get some feedback as to what kind of an API might make sense, and how much/where you'd be likely to use these types so we can make sure they would work for you.

**Comment by panesofglass** [comment]
@kolektiv I was thinking separate repositories, but separate namespace can also work.

**Comment by haf** [comment]
+1 on separate repo/lib. But if they are separate nugets without dependencies, it shouldn't matter too much.

I'd really like to participate in a spike to get it integrated into Suave. I can't start the spike myself, as I have a fair bit on my plate right now -- I'd read over your shoulder and participate though.

Also interested in the question about the parser; an online/yielding parser might be better in some cases, but it's also possible to do it as an optimisation later.

**Comment by kolektiv** [comment]
Right, so i've begun breaking it in to a separate repo here: https://github.com/freya-fs/arachne

So far i've just pulled the types across, and dropped the lenses which are Freya specific (i.e. the Request.* and Response.* lenses which are from the FreyaState to the relevant chunk of data in the OWIN dictionary). Those don't really make sense in here, although lenses in to the data structures of the types do make sense - one day when I have a chance to write them all!

I haven't done anything about FParsec/ParsecClone - that's a back burner item for now I think. Next step is to get the tests in and get it building/published, so I can branch Freya and create a new Freya version which depends on the new Arachne libs.

On a different note, @serialseb and @darrelmiller ... I've had a quick play at using the types from C# and at the moment it looks like there would be a serious amount of effort involved in making them feel usable. They're essentially all union types, so most of the data doesn't show up in any way that C# understands. I haven't looked through the code that @mausch suggests fully, but I'm not sure there's a straightforward way of exposing unions to C# (hence the framework design guidelines, etc. yes! :) ) I'm happy to try and explore what it would take to create a C# friendly wrapper on top if anyone has any good patterns for exposing that kind of data structure to C#?

At the very least I hope it might be useful to Suave as it is (once those tests and build are done anyway).

**Comment by mausch** [comment]
On exposing DUs to C# see http://bugsquash.blogspot.com/2012/03/algebraic-data-type-interop-f-c.html , it's very easy.

**Comment by panesofglass** [comment]
@kolektiv, looks like we really don't need to do anything. The `Match` extension @mausch points out is a simple helper that does the `is` or `as` type evaluations that one would otherwise do in C#. @serialseb and @darrelmiller will likely use those or a Visitor pattern to break up the parsed AST, where necessary. It's also possible one or the other may come up with a nice library to layer on top for consuming Arachne from C#.

**Comment by kolektiv** [comment]
I'm all for things that don't require extra work! Happy to hear from
@serialseb and @darrelmiller if there's anything we can add which will make
their lives easier, more than willing to help.

**Comment by panesofglass** [comment]
Arachne is now available on [nuget](http://nuget.org/packages/Arachne)
