### ISSUE TITLE
Build Enhancements

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#71]
- [x] Documentation Gen - transferred to [Read the Docs](http://docs.freya.io/)
- [x] Switch NuGet to Paket Pack/Push

**Comment by panesofglass** [comment]
Bad news: `Paket.Pack` requires [paket.template](https://github.com/fsprojects/ProjectScaffold/blob/master/src/FSharp.ProjectTemplate/paket.template) files in every project directory. This will render your typed descriptions in the build unusable. I also don't see a way to add dependencies through the paket.template file, so I think we may be SOL on using `Paket.Pack`.

/cc @forki

**Comment by forki** [comment]
What do you propose to change in paket?

**Comment by mavnn** [comment]
It adds dependencies for projects automatically for projects, or you can add them manually and put the file wherever you want. I'm not sure what you mean by "typed descriptions"?

**Comment by mavnn** [comment]
Had a look at the build.fsx; moving to paket pack should allow you to remove all of the dependencies you're manually tracking in the build.fsx. It does mean ending up with a paket.template file in the same directory as each project you want to package, but you could write those automatically in a similar way to the AssemblyInfo updates.

The only one you'd need to construct a manual dependency list for is the metapackage, I think.

**Comment by panesofglass** [comment]
@forki and @mavnn, how would we add dependencies on packages that are not yet deployed? All projects in Freya are intended to be deployed independently and take dependencies on one another. I assume `Paket.Pack` uses `paket.references` to build the dependencies. Will it fail to work if we name them {Project.Name}.paket.references?

**Comment by mavnn** [comment]
If you put a <proj file name>.paket.template file which is ``type project``
(see the docs) in the same directory it will package the build output of
the project.

It will automatically add dependencies on based on paket.references but
also on any project refs - either as a package dependency if that project
has a matching template file, or by copying the build output into the
package if it doesn't.

**Comment by panesofglass** [comment]
@mavnn, I think I need a tutorial, but this sounds fantastic. Thanks!

**Comment by panesofglass** [comment]
Done in #129
