### ISSUE TITLE
New Extension-Friendly HTTP Graph

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#73]
Redesign HTTP graph to be more amenable to extensions, with less logic duplication, and friendliness to things like PATCH support.

**Comment by panesofglass** [comment]
Done!

**Comment by kolektiv** [comment]
I'm not sure this is done as such - it's ok for now though, i'm not going to try and change it before next talks/workshops!

**Comment by panesofglass** [comment]
Well, we did merge it into master. I think any additional items should be ticketed independently, if that is okay with you.
