### ISSUE TITLE
Merge Integration into Pipeline?

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#75]
Now that we are up to .NET 4.5, we could merge the Integration project into the Pipeline project. Thoughts?

**Comment by panesofglass** [comment]
@kolektiv, thoughts? I'm happy to merge them since we are dependent on OWIN. If so, let's move it into milestone 1.0.

**Comment by kolektiv** [comment]
Yeah why not - it seems sensible to me if it's possible, one less library around that will reduce confusion potentially. Go for it I think!
