### ISSUE TITLE
URI Templates - Router

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/freya#83]
The new URI Template based router, while more powerful, needs to have execution recording designed and wired in.

**Comment by panesofglass** [comment]
Status update?

**Comment by kolektiv** [comment]
Looking through my code, this needs a little more work to record the URI template derived routing trie. But it's not far off. I may try and get this bit done tonight, at which point I think URI Template based routing and the surrounding changes may be ready to go in to freya-fs from my branch. develop definitely, maybe master...?

**Comment by panesofglass** [comment]
I'm for moving stuff to master as quickly as possible.

**Comment by kolektiv** [comment]
Yeah I agree at this stage. PR #90 is now available!
