### ISSUE TITLE
HEAD throws an exception for a valid resource

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#84]
System.Net.ProtocolViolationException was unhandled by user code
Message: An exception of type 'System.Net.ProtocolViolationException' occurred in Microsoft.Owin.Host.HttpListener.dll but was not handled in user code
Additional information: Bytes to be written to the stream exceed the Content-Length bytes size specified.

**Comment by kolektiv** [comment]
This is a slightly interesting one. The existing HTTP graph modified from the webmachine/liberator world doesn't really deal with HEAD sanely as far as I can tell. I think it's probably a sign that I should probably prioritise #73 higher shortly...

**Comment by panesofglass** [comment]
Let's get this in for milestone 1.0. Did you find the issue, by chance?

**Comment by kolektiv** [comment]
I think so... Not quite decided on the "right" fix, but will shortly - definitely for 1.0 though.
