### ISSUE TITLE
Get HEAD for free with GET method enable

### ISSUE THREAD

**Issue by WilliamBerryiii** [freya-fs/freya#85]
I would like to propose that HEAD come for free with GET.

**Comment by panesofglass** [comment]
That sounds reasonable. What do you think, @kolektiv?

**Comment by kolektiv** [comment]
I need to have a bit of a think about the right way to express this in the graph. It does sound reasonable, the only concern I have is that at the moment all of the Machine configuration is *extremely* explicit. I worry about "implicit" functionality like this as being potentially surprising. Also, I don't want to restrict people from exposing GET but *not* HEAD if they wish/need to (I will admit I can't think of a case where I've needed that, but I can imagine a requirement for a minimum viable surface).

At the moment, the default actions exposed by a machine without override are [ GET; HEAD ], so it is *sort of* free at the moment - but it doesn't actually behave correctly. This is definitely one I want to fix "right"!

@WilliamBerryiii - what do you think? Thank you for raising the thought, I genuinely appreciate it, I'm happy to be told I'm worrying too much if you really think so :)

**Comment by WilliamBerryiii** [comment]
I would hazard a guess to say that [head] is left unimplemented more often then not out of ignorance/laziness/lack of time than because of a strategic decision.  Having it implemented out of the gate may be an opportunity encouraging developers to have the caching/existence conversation earlier in the design/implementation process.

**Comment by panesofglass** [comment]
Per RFC 7231, servers MUST support the `HEAD` method, but I don't see any explicit mention that every resource MUST or even SHOULD support `HEAD`. Let's make it free to add `HEAD` with no other overrides, but not implied to accompany `GET`. I recall explicitly denying `HEAD` in the past b/c of some badly behaved User-Agents. That was probably a mistake, but it's possible others may want to deny support for `HEAD` arbitrarily.

**Comment by kolektiv** [comment]
It needs to work correctly (and with no extra work) when you support HEAD (which it doesn't seem to right now) but I think I'm going to settle on "implicit" head being out of scope. I'm going to close this one and open an issue (if there's not one) on HEAD seeming to be broken. @WilliamBerryiii thanks again for your thoughts and input :)
