### ISSUE TITLE
Add HTTP2 graph as another extension

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/freya#86]
See http://http2.github.io/

**Comment by kolektiv** [comment]
This is kind of an interesting one - do we think it'll have an impact at the Freya level, or is this more in the realms of the OWIN compatible server layer? I think we're really only dealing with the HTTP semantics (which haven't changed much I think), but if there's something we can do here to make something better, happy to see what that could be!

**Comment by panesofglass** [comment]
Yes, I was thinking in terms of the HTTP semantics. I also don't know that anything substantially changes, but I think it worth the exercise to find out and provide a graph if there are differences between 1.1 and 2.0.

**Comment by kolektiv** [comment]
Yeah I agree on that :)

**Comment by kolektiv** [comment]
Having looked at this, i'm not sure there's much we can support here at the moment, so closing this for now, in the expectation that if concrete requirements appear, we'll support them.
