### ISSUE TITLE
NuGet package points to a bad projectUrl

### ISSUE THREAD

**Issue by ferventcoder** [freya-fs/freya#96]
https://www.nuget.org/packages/Freya.Machine/0.11.0-alpha-173 has a project url of http://freya-fs.github.com/freya - I noticed that is giving an error this morning. Not sure if it is related to github going down earlier or not. Anyway, just wanted to give you a heads up!

**Comment by panesofglass** [comment]
Thanks, @ferventcoder! I think this is b/c @kolektiv just made some changes for docs to point to http://docs.freya.io/en/latest/. I will make that change in our build script. Cheers!

**Comment by kolektiv** [comment]
I wish I could blame GitHub, but that seems more like our fault (likely mine!) Thanks for spotting that and letting us know, many thanks :smile:

I've just fixed that in the NuGet template!

**Comment by kolektiv** [comment]
Oh no! A maintainer race condition!

**Comment by kolektiv** [comment]
(Incidentally, the incorrect URLs were in the nuget template, so they'll get correctly picked up the next time we push a release to NuGet. I have high hopes that might even be 1.0...

**Comment by panesofglass** [comment]
@kolektiv, :) I was just wondering why I couldn't find that URL in the `template.nuspec`. You must have beaten me to it.

**Comment by panesofglass** [comment]
Looks like a build is imminent since you did not use `[skip ci]` in the commit message. That should resolve the problem. We _are_ auto-deploying to NuGet, right?

**Comment by kolektiv** [comment]
Well, i'd disabled the publishing key, so it won't be pushing this time...
(Also, I was entirely unaware of [skip ci], so that's good to know!)
